/*  DialogBoxInput, version 2
*   Catching the exception generated by the parseInt method
*   Anderson, Franceschi
*/

import javax.swing.JOptionPane;

public class DialogBoxInput
{
  public static void main( String [] args )
  {
    int n = 0;  // declare and initialize variable

    // prompt for input
    String s = JOptionPane.showInputDialog( null,
                             "Enter an integer" );
    System.out.println( "You entered " + s );

    try
    {
       // attempt to convert the String to an int
       n = Integer.parseInt( s );
       System.out.println( "Conversion was successful." );
    }
    catch ( NumberFormatException nfe )
    {
       System.out.println( "Sorry. incompatible data." );
       System.out.println( "\nOutput from getMessage: \n"
                           + nfe.getMessage( ) );

       System.out.println( "\nOutput from toString: \n"
                           + nfe.toString( ) );
       System.out.println( "\nOutput from printStackTrace: " );
       nfe.printStackTrace( );
    }

    System.out.println( "\nn is " + n );
  }
}
