/*  An Exception Generated by the parseInt Method
*   Anderson, Franceschi
*/

import javax.swing.JOptionPane;

public class DialogBoxInput
{
  public static void main( String [] args )
  {
    // prompt for input; return value is a String
    String s = JOptionPane.showInputDialog( null,
                             "Enter an integer" );
    System.out.println( "You entered " + s );

    // attempt to convert the String to an int
    int n = Integer.parseInt( s );
    System.out.println( "Conversion was successful. "
                        + "The integer is " + n );
  }
}
